version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=gestion_produits
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
  minio:
    image: minio/minio:RELEASE.2019-03-20T22-38-47Z
    volumes:
      - ./minio_storage/:/export
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio-admin
      MINIO_SECRET_KEY: minio-password
    command: server /export
  web:
    build: .
    ports:
      - "8080:80"
    links:
      - db
      - minio
    environment:
      MYSQL_HOST: db
